### ISSUE TITLE
how do we increase the spawn delay?

### ISSUE THREAD

**Issue by Driwen4356** [NopeNotDark/SpawnerX#2]
I want to increase the spawn delay,
I change in the plugin but nothing is done
![image](https://github.com/NopeNotDark/SpawnerX/assets/125693577/a803d08d-c392-4dbd-b346-442f9d1007a2)

**Comment by NopeNotDark** [comment]
Currently I do not have this be fully customizable, planning on adding this in the future, but if you want to turn up the spawn rate, I would recommend setting the repeating task be below 20, this value is located under https://github.com/NopeNotDark/SpawnerX/blob/main/src/nopenotdark/block/tile/MonsterSpawnerTile.php

**Comment by NopeNotDark** [comment]
Also those are ticks not how many will spawn, 20 ticks is 1 second.
