### ISSUE TITLE
start with stack of 3 ?

### ISSUE THREAD

**Issue by Driwen4356** [NopeNotDark/SpawnerX#3]
When a mob spawns, it spawns directly in 3 stacks, Where in the code can I set it to start spawning by 1x?

![image](https://github.com/NopeNotDark/SpawnerX/assets/125693577/39cb88cd-e09e-4385-b65d-233399f69484)

**Comment by NopeNotDark** [comment]
Currently there is no way to turn off stacking entities, I don't have much time to implement configurability right now but will do in the future.

**Comment by Driwen4356** [comment]
Ok there is no config but in the code can you tell me where can I modify that pls

**Comment by NopeNotDark** [comment]
You can't it auto stacks the entities into one entity.
